sudo: required

services:
  - docker

script:
  - docker build -t prodrink/prodrink-catalog .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push prodrink/prodrink-catalog:latest
